# Generated by Django 5.0.7 on 2024-09-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mcneese_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pointsum",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin",
            field=models.URLField(
                blank=True, default="http://www.linkedin.com", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Black/African-American/Afro-Latinx",
                        "Black/African-American/Afro-Latinx",
                    ),
                    ("Hispanic/Latinx(Non-White)", "Hispanic/Latinx(Non-White)"),
                    ("Native American/Alaska Native", "Native American/Alaska Native"),
                    ("Asian/Asian-American", "Asian/Asian-American"),
                    ("White(Non-Hispanic/Latinx)", "White(Non-Hispanic/Latinx)"),
                    ("Middle-Eastern", "Middle-Eastern"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
