# Generated by Django 5.0.7 on 2024-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_mcneese_id_remove_user_pointsum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="class_standing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Freshman", "Freshman"),
                    ("Sophomore", "Sophomore"),
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("Graduate", "Graduate"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Accounting", "Accounting"),
                    ("Agricultural Sciences", "Agricultural Sciences"),
                    ("Art", "Art"),
                    ("Biological Science", "Biological Science"),
                    ("Biology Education Grades 6-12", "Biology Education Grades 6-12"),
                    ("Business Administration", "Business Administration"),
                    ("Chemical Engineering", "Chemical Engineering"),
                    ("Chemistry", "Chemistry"),
                    ("Computer Science", "Computer Science"),
                    ("Criminal Justice", "Criminal Justice"),
                    (
                        "Early Childhood Education Grades PK-3",
                        "Early Childhood Education Grades PK-3",
                    ),
                    ("Education Grades K-12", "Education Grades K-12"),
                    ("Electrical Engineering", "Electrical Engineering"),
                    (
                        "Elementary Education Grades 1-5",
                        "Elementary Education Grades 1-5",
                    ),
                    ("Engineering", "Engineering"),
                    ("English", "English"),
                    ("Family Science", "Family Science"),
                    ("Finance", "Finance"),
                    ("Food Technology", "Food Technology"),
                    ("General Studies", "General Studies"),
                    ("Health and Physical Education", "Health and Physical Education"),
                    (
                        "Health and Physical Education Grades K-12",
                        "Health and Physical Education Grades K-12",
                    ),
                    ("Health Systems Management", "Health Systems Management"),
                    ("History", "History"),
                    ("Humanities", "Humanities"),
                    ("Kinesiology", "Kinesiology"),
                    (
                        "Liquefied Natural Gas Business",
                        "Liquefied Natural Gas Business",
                    ),
                    ("Management", "Management"),
                    ("Marketing", "Marketing"),
                    ("Mass Communication", "Mass Communication"),
                    ("Math Education Grades 6-12", "Math Education Grades 6-12"),
                    ("Mathematical Sciences", "Mathematical Sciences"),
                    ("Mechanical Engineering", "Mechanical Engineering"),
                    ("Medical Laboratory Science", "Medical Laboratory Science"),
                    (
                        "Middle School Education Grades 4-8 [Mathematics]",
                        "Middle School Education Grades 4-8 [Mathematics]",
                    ),
                    (
                        "Middle School Education Grades 4-8 [Science]",
                        "Middle School Education Grades 4-8 [Science]",
                    ),
                    (
                        "Multiple Levels Grades K-12 [Art]",
                        "Multiple Levels Grades K-12 [Art]",
                    ),
                    (
                        "Multiple Levels Grades K-12 [Music-Instrumental]",
                        "Multiple Levels Grades K-12 [Music-Instrumental]",
                    ),
                    (
                        "Multiple Levels Grades K-12 [Music-Vocal]",
                        "Multiple Levels Grades K-12 [Music-Vocal]",
                    ),
                    ("Music", "Music"),
                    ("Music Education", "Music Education"),
                    (
                        "Natural Resource Conservation Management",
                        "Natural Resource Conservation Management",
                    ),
                    ("Nursing", "Nursing"),
                    ("Nursing LPN to BSN", "Nursing LPN to BSN"),
                    ("Nursing RN to BSN", "Nursing RN to BSN"),
                    ("Nutrition and Dietetics", "Nutrition and Dietetics"),
                    ("Political Science", "Political Science"),
                    ("Pre-Physical Therapy", "Pre-Physical Therapy"),
                    ("Psychology", "Psychology"),
                    ("Radiologic Sciences", "Radiologic Sciences"),
                    ("Radiologic Sciences RT to BS", "Radiologic Sciences RT to BS"),
                    ("School Librarian", "School Librarian"),
                    (
                        "Secondary Education Grades 6-12 [Agriculture]",
                        "Secondary Education Grades 6-12 [Agriculture]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [Biology]",
                        "Secondary Education Grades 6-12 [Biology]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [Business]",
                        "Secondary Education Grades 6-12 [Business]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [Chemistry]",
                        "Secondary Education Grades 6-12 [Chemistry]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [English]",
                        "Secondary Education Grades 6-12 [English]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [Environmental Science]",
                        "Secondary Education Grades 6-12 [Environmental Science]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [General Science]",
                        "Secondary Education Grades 6-12 [General Science]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [Mathematics]",
                        "Secondary Education Grades 6-12 [Mathematics]",
                    ),
                    (
                        "Secondary Education Grades 6-12 [Social Studies]",
                        "Secondary Education Grades 6-12 [Social Studies]",
                    ),
                    ("Sociology", "Sociology"),
                    (
                        "Special Education Mild/Moderate for Elementary Education Grades 1-5",
                        "Special Education Mild/Moderate for Elementary Education Grades 1-5",
                    ),
                    ("Sports Medicine", "Sports Medicine"),
                    ("Theatre Arts", "Theatre Arts"),
                    ("Other", "Other"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
