# Generated by Django 5.2.9 on 2025-12-31 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_eventattendance_qr_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventattendance",
            name="qr_token",
        ),
    ]
