# Generated by Django 5.2.9 on 2025-12-31 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_eventattendance_qr_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendance",
            name="qr_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
