# Generated by Django 5.0.7 on 2024-10-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="forgot_password_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
    ]
