# Generated by Django 5.0.7 on 2024-10-17 17:02

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("api", "0005_remove_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=address.models.AddressField(
                on_delete=django.db.models.deletion.CASCADE, to="address.address"
            ),
        ),
    ]
