# Generated by Django 5.0.7 on 2024-10-30 14:25

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pointsum",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="points",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(100),
                    api.models.multiple_of_ten,
                ],
            ),
        ),
    ]
